<a href="https://colab.research.google.com/github/suryakanthPS/DS-Workbooks/blob/main/0724_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Univariate Feature Selection

In [ ]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [ ]:
# load data
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

In [ ]:
# feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)
#what are the feature that's affective the class coloumn..For that use SelectKBest

In [ ]:
# summarize scores
set_printoptions(precision=3) #precision 3 will give us 3decimal values
print(fit.scores_)
features = fit.transform(X)


#For regression: f_regression, mutual_info_regression
#For classification: chi2, f_classif, mutual_info_classif

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [ ]:
dataframe.head()
#from the above result we find that test has higest feature value then plas
#so these values affects the class more

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [ ]:
#univariant works on chisquare based it gives test,plas,age,mass are the main feature affecting the class

#### Recursive Feature Elimination

In [ ]:
# Feature Extraction with RFE
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# load data
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
model = LogisticRegression(max_iter=400)
rfe = RFE(model)
fit = rfe.fit(X, Y)


In [ ]:
#Num Features: 
fit.n_features_
#from the result the 4 feature affects the  class

4

In [ ]:
#Selected Features:
fit.support_
#preg,plas,mass,pedi

array([ True,  True, False, False, False,  True,  True, False])

In [ ]:
# Feature Ranking:
fit.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

In [ ]:
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [ ]:
#RFE works on probability & Rsquare based it gives preg,plas,mass,pedi 
#are the main feature affecting the class

#### Feature Importance using Decision Tree

In [ ]:
# Feature Importance with Extra Trees Classifier
from pandas import read_csv
from sklearn.tree import  DecisionTreeClassifier
# load data
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
model = DecisionTreeClassifier()
model.fit(X, Y)
print(model.feature_importances_)

[0.053 0.31  0.079 0.027 0.033 0.256 0.123 0.12 ]


In [ ]:
#tree based feature selection works on Information gain orGINI index it gives plas,mass,pedi,age 
#are the main feature affecting th

## Feature Selection is Subjective and is best judged based on your understanding of Dataset and Experience

*   SelectKbest for Classification
*   RFE/Backware elimination for MLR or Regression Based Problems 
*   Decision Tree is another method but it may vary results as the tree keeps growing
